kinematic_variable: "LQ"
embedding_variable: "embedding"
distance: "euclidean"
sigsig_eff: 0.2
linking_length:
hidden_sizes_gcn: [24, 24, 24, 24, 24]
hidden_sizes_mlp: []
LR: 0.01
dropout_rates: [0.0, 0.0, 0.0, 0.0, 0.0]
epochs: 30
num_nb_list: [20, 20]
batch_size: 1024
gnn_type: "GAT"