kinematic_variable: "LQ_HighLevel"
embedding_variable:
distance: "euclidean"
friend_graph: True
edge_weights: True
edge_frac: 0.05
targettarget_eff: 
linking_length:
#hidden_sizes_gcn: [32, 32, 32, 32]
hidden_sizes_gcn: []
hidden_sizes_mlp: [5,5]
#dropout_rates: [0, 0, 0, 0, 0, 0]
dropout_rates: [0,0] # has to be int?
LR: 0.0003 # to 0.001
patience_LR: 3
num_nb_list: [60, 6]
batch_size: 2048 # best: 2048
gnn_type: "GCN"
epochs: 50
patience_early_stopping: 40
single_fold:
plot_conv_kinematics: False

