kinematic_variable: "LQ_LowLevel"
embedding_variable:
distance: "emd"
friend_graph: True
edge_weights: True
edge_frac: 0.1
targettarget_eff: 
linking_length:
hidden_sizes_gcn: []
hidden_sizes_mlp: [8, 8]
dropout_rates: [0, 0]
LR: 0.1
patience_LR: 3
num_nb_list: []
batch_size: 256
gnn_type: "DNN"
epochs: 50
patience_early_stopping: 50
single_fold: 1
plot_conv_kinematics: False
