kinematic_variable: "LQ_HighLevel"
embedding_variable:
distance: "euclidean"
friend_graph: True
edge_weights: True
edge_frac:
targettarget_eff: 
linking_length: 1
hidden_sizes_gcn: [12, 12]
hidden_sizes_mlp: [12, 12]
dropout_rates: [0, 0, 0, 0]
LR: 0.01
patience_LR: 3
num_nb_list: [10, 10, 10]
#[120, 120, 120]
batch_size: 128
gnn_type: "GCN"
epochs: 50
patience_early_stopping: 20
single_fold:
plot_conv_kinematics: True