#######################
# user config for Holly
#######################

# signal model hhh, LQ, stau
signal: LQ
signal_mass: 1000
backgrounds: ["singletop", "ttbar"]
cuts:
  met:
    threshold: 200
    operation: ">"
feature_dim:
distance:
  euclidean:
  cosine:
  emd:
    objects: ["bjet1", "bjet2", "lep1", "lep2"]
run_with_cuda: False
n_folds: 2

# input paths
ntuple_path: /data/atlas/users/pacey/GNN/ntuples/LQs_140325/
feature_h5_path: /data/atlas/users/pacey/GNN/data/sliced/
kinematic_h5_path: /data/atlas/users/pacey/GNN/data/sliced/
ll_path: /data/atlas/users/pacey/GNN/linking_lengths/
dist_path: /data/atlas/users/pacey/GNN/distances/

# output paths
plot_path: /data/atlas/users/pacey/GNN/plots/ 
adj_path: /data/atlas/users/pacey/GNN/graph/
model_path: /data/atlas/users/pacey/GNN/models/
score_path: /data/atlas/users/pacey/GNN/scores/ 
