#######################
# user config for Holly
#######################

# signal model hhh, LQ, stau
signal: LQ
signal_mass: 1000
backgrounds: ["singletop", "ttbar"]
cuts:
  - name: met
    threshold: 200
    operation: ">"
feature_dim:
run_with_cuda: True
n_folds: 3

# input paths
ntuple_path: /data/atlas/users/pacey/GNN/ntuples/LQs_080925/
feature_h5_path: /data/atlas/users/pacey/GNN/data/sliced_2/
kinematic_h5_path: /data/atlas/users/pacey/GNN/data/sliced_2/
ll_path: /data/atlas/users/pacey/GNN/linking_lengths/
dist_path: /data/atlas/users/pacey/GNN/distances/

# output paths
plot_path: /data/atlas/users/pacey/GNN/plots/ 
adj_path: /data/atlas/users/pacey/GNN/graph/
model_path: /data/atlas/users/pacey/GNN/models/
score_path: /data/atlas/users/pacey/GNN/scores/ 
