#######################
# user config for Maggie
#######################

# signal model hhh, LQ, stau
signal: LQ
signal_mass: 1000
backgrounds: ["singletop", "ttbar"]
cuts:
  met:
    threshold: 0
    operation: ">"
feature_dim:

# input paths
ntuple_path: /data/atlas/users/pacey/GNN/ntuples/LQs_140325/
feature_h5_path: /data/atlas/atlasdata3/maggiechen/gnn_project/data/LQ_split_files/MetCut200_140325/
kinematic_h5_path: /data/atlas/atlasdata3/maggiechen/gnn_project/data/LQ_split_files/MetCut200_140325/
ll_path: /data/atlas/atlasdata3/maggiechen/gnn_project/trained_models/MetCut200_140325/linking_lengths/ 
dist_path: /data/atlas/atlasdata3/maggiechen/gnn_project/trained_models/MetCut200_140325/distances/
score_path: /data/atlas/atlasdata3/maggiechen/gnn_project/trained_models/MetCut200_140325/output_scores/

# output paths
plot_path: /data/atlas/atlasdata3/maggiechen/gnn_project/trained_models/MetCut200_140325/plots/ 
adj_path: /data/atlas/atlasdata3/maggiechen/gnn_project/trained_models/MetCut200_140325/graph/
model_path: /data/atlas/atlasdata3/maggiechen/gnn_project/trained_models/MetCut200_140325/models/
