#######################
# user config for Maggie
#######################

# signal model hhh, LQ, stau
signal: hhh

# input paths
ntuple_path: /data/atlas/atlasdata3/maggiechen/HHH6b_pairing/post-processing/20231008/
h5_path: /data/atlas/atlasdata3/maggiechen/gnn_project/data/hhh_split_files/ 
ll_path: /data/atlas/atlasdata3/maggiechen/gnn_project/tests/linking_lengths/ 
dist_path: /data/atlas/atlasdata3/maggiechen/gnn_project/tests/distances/

# output paths
plot_path: /data/atlas/atlasdata3/maggiechen/gnn_project/tests/plots/ 
adj_path: /data/atlas/atlasdata3/maggiechen/gnn_project/tests/graph/
model_path: /data/atlas/atlasdata3/maggiechen/gnn_project/tests/models/ 
