#######################
# user config for Maggie
#######################

# signal model hhh, LQ, stau
signal: LQ
variable: LQ_LowLevel
signal_mass: 1000
backgrounds: ["singletop", "ttbar"]
cuts:
  met:
    threshold: 0
    operation: ">"

feature_dim:

ntuple_path: /data/atlas/users/pacey/GNN/ntuples/LQs_110425_small/
h5_path: /data/atlas/atlasdata3/maggiechen/gnn_project/data/LQ_split_files/large_MetCut200/

# save paths
model_path: /data/atlas/atlasdata3/maggiechen/gnn_project/GraphBuilder/models/same_class_clustering/LowLevelKinematics_MetCut200/
plot_path: /data/atlas/atlasdata3/maggiechen/gnn_project/GraphBuilder/scan_plots/same_class_clustering/LowLevelKinematics_MetCut200/
embedding_path: /data/atlas/atlasdata3/maggiechen/gnn_project/GraphBuilder/embeddings/same_class_clustering/LowLevelKinematics_MetCut200/
# training parameters
margin: 0.1
LR: 0.1
embedding_dim: 12
epoch: 30
penalty: 20
