#######################
# user config for Maggie
#######################

# signal model hhh, LQ, stau
signal: LQ
variable: LQ

# input paths
ntuple_path: /data/atlas/atlasdata3/maggiechen/LQ_ntuples/
h5_path: /data/atlas/atlasdata3/maggiechen/LQ_test/

# save paths
model_path: /data/atlas/atlasdata3/maggiechen/gnn_project/GraphBuilder/models/
plot_path: /data/atlas/atlasdata3/maggiechen/gnn_project/GraphBuilder/scan_plots/

# training parameters
margin: 2
LR: 0.01
embedding_dim: 24
epoch: 30
penalty: 4